### ISSUE TITLE
게시글 정보 필터링 적용이 안됨

### ISSUE THREAD

**Issue by ohsonghyun** [TeamDev6/re-jord-be#99]
## 버그

![image](https://user-images.githubusercontent.com/63629844/235394705-10584dd3-7f7c-4075-baf1-b4027184a6b4.png)

## 해당 API

![image](https://user-images.githubusercontent.com/63629844/235394772-c057c1aa-4bf2-4607-a57d-54f1d8d0eb6b.png)

## 에러 로그

에러 로그 첨부 가능하면 부탁드립니다

## 버그 재현 방법

버그가 발생한 조작 방법을 구체적으로 기재해주세요.

**Comment by pullingoff** [comment]
withUid로 한 유저의 게시글 API 입니다!
